version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - cd environments/dev
      - terraform init
  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
